import { StyleSheet } from "react-native";

export const SessionInforStyle = StyleSheet.create({
  SessionInfor: {
    paddingTop: 30,
    flexDirection: "column",
    paddingHorizontal: 25,
    justifyContent: "space-evenly",
    flexWrap: "nowrap",
    width: "98%",
    alignItems: "center",
    height: "25%",
    backgroundColor: "white",
    borderRadius: 30,
    marginHorizontal: 5,
    gap: 0,
    shadowColor: "black",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  ViewTop: {
    marginTop: 0,
    width: "95%",
    borderBottomWidth: 3,
    borderBottomColor: "#f3bfd2",
    paddingBottom: 20,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  ViewBottom: {
    marginTop: 0,
    top: 0,
    flexDirection: "row",
    flexWrap: "nowrap",
  },
  // bottom item
  ViewBottomIterm: {
    flex: 1,
    height: 70,
    paddingBottom: 10,
    borderLeftColor: "#ddd",
    borderLeftWidth: 5,
    flexDirection: "column",
    gap: 7,
    justifyContent: "center",
    alignItems: "center",
  },
  ViewBottomItermF: {
    flex: 1,
    height: 70,
    paddingBottom: 10,
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    gap: 7,
  },
  ImageBottom: {
    width: 40,
    height: 40,
    tintColor: "red",
  },
  TextBottom: {
    color: "red",
  },
  // top item
  ViewCoin: {
    flex: 1,
    flexWrap: "nowrap",
    flexDirection: "row",
    gap: 5,
    justifyContent: "flex-start",
    alignItems: "flex-end",
  },
  ViewMember: {
    flex: 1,
    flexWrap: "nowrap",
    flexDirection: "row",
    gap: 5,
    justifyContent: "flex-start",
    alignItems: "flex-end",
  },
});
